# Form implementation generated from reading ui file 'C:\Users\ASUS\PycharmProjects\K22416C\Final\code_pyqt6\LoginMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1040, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelbackgrourd = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelbackgrourd.setGeometry(QtCore.QRect(10, 10, 1011, 541))
        self.labelbackgrourd.setText("")
        self.labelbackgrourd.setPixmap(QtGui.QPixmap("C:\\Users\\ASUS\\PycharmProjects\\K22416C\\Final\\code_pyqt6\\../image/pic4.jpg"))
        self.labelbackgrourd.setScaledContents(True)
        self.labelbackgrourd.setWordWrap(False)
        self.labelbackgrourd.setOpenExternalLinks(False)
        self.labelbackgrourd.setObjectName("labelbackgrourd")
        self.lineusername = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineusername.setGeometry(QtCore.QRect(630, 221, 331, 51))
        self.lineusername.setStyleSheet("background-color: rgb(230, 230, 230);\n"
"color: rgb(0, 0, 0);")
        self.lineusername.setObjectName("lineusername")
        self.linepassword = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.linepassword.setGeometry(QtCore.QRect(630, 320, 331, 51))
        self.linepassword.setStyleSheet("background-color: rgb(230, 230, 230);\n"
"color: rgb(0, 0, 0);")
        self.linepassword.setObjectName("linepassword")
        self.pushButtonlogin = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonlogin.setGeometry(QtCore.QRect(850, 420, 111, 41))
        self.pushButtonlogin.setStyleSheet("font: 12pt \"Sitka\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(230, 230, 230);")
        self.pushButtonlogin.setObjectName("pushButtonlogin")
        self.label_username = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_username.setGeometry(QtCore.QRect(630, 200, 111, 21))
        self.label_username.setStyleSheet("font: 12pt \"Sitka\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.label_username.setObjectName("label_username")
        self.label_password = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_password.setGeometry(QtCore.QRect(630, 300, 111, 21))
        self.label_password.setStyleSheet("font: 12pt \"Sitka\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.label_password.setObjectName("label_password")
        self.label_creditcard = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_creditcard.setGeometry(QtCore.QRect(60, 40, 931, 101))
        self.label_creditcard.setStyleSheet("font: 36pt \"Showcard Gothic\";\n"
"color: rgb(255, 255, 255);")
        self.label_creditcard.setObjectName("label_creditcard")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1040, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonlogin.setText(_translate("MainWindow", "Login"))
        self.label_username.setText(_translate("MainWindow", "User Name"))
        self.label_password.setText(_translate("MainWindow", "Password"))
        self.label_creditcard.setText(_translate("MainWindow", "Credit Card Fraud Detection"))
